### PR TITLE
(Issue#20) Replace markdown-imenu-create-index with new function.

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by waynr** [comment]
This seems to work for me.

**Comment by waynr** [comment]
Now that I think about it a little more, a more robust fix would probably be to check for the existence of the `markdown-imenu-create-index` function, then if it doesn't exist define it using `markdown-imenu-create-nested-index`.

Is there a way to check which version of a dependent package is installed in elisp? This is actually my first time modifying elisp outside a spacemacs configuration file.

**Comment by ardumont** [comment]
I can't show you but markdown-mode defines a variable that held the
obsolete function you mentioned.

So maybe yet another approach would be to use this variable and define one
for markdown-toc. Maybe using the new one you also mention.

I think checking emacs package version is not a good idea. I may need to
declare an updated version of markdown-mode in markdown-toc header.

Again it's speculation for now.
I have not a working network or computer only a phone which is very tedious
right now.

Huge thx for helping though!

Cheers,

**Comment by ardumont** [comment]
Thanks again.

**Pull request merged**
